### PR TITLE
Enable USB ACM

### PR DESCRIPTION
**Pull request by s00se**
This enables USB ACM for accessing USB peripherals

### CODE REVIEW

**Comment by thestinger** [comment]
Does enabling this driver accomplish something? You aren't explaining why you want it enabled and if you've tested whether having it enabled provides the functionality you want. In all likelihood, it's not going to accomplish something because the OS probably doesn't know how to use it and it won't be accessible to apps.

```
config USB_ACM
	tristate "USB Modem (CDC ACM) support"
	depends on TTY
	---help---
	  This driver supports USB modems and ISDN adapters which support the
	  Communication Device Class Abstract Control Model interface.
	  Please read <file:Documentation/usb/acm.txt> for details.

	  If your modem only reports "Cls=ff(vend.)" in the descriptors in
	  /sys/kernel/debug/usb/devices, then your modem will not work with this
	  driver.

	  To compile this driver as a module, choose M here: the
	  module will be called cdc-acm.

**Comment by s00se** [comment]
> Does enabling this driver accomplish something? 

Enabling this driver "accomplishes" allowing users and applications to interact with USB peripherals that use/require ACM support.

> You aren't explaining why you want it enabled and if you've tested whether having it enabled provides the functionality you want.

See above. Please let me know how one can "prove" that it does enable the desired functionality, so it can be provided, and we can continue discussion on merging.

> In all likelihood, it's not going to accomplish something because the OS probably doesn't know how to use it and it won't be accessible to apps.

Unless GrapheneOS, outside of the modifications to accessing USB accessories during boot/unlock state, severely breaks how AOSP interacts with USB peripherals, this accomplishes exactly what is requested. 

Perhaps we can discuss the benefits or downsides of having this included instead of the conjecture of the "*likelihood*" of accomplishing *something* because the OS *probably doesn't know* when it's pretty easy to build a kernel with this enabled and refute this weird *maybe possible could be perhaps* scenario provided.

**Comment by ghost** [comment]
> Enabling this driver "accomplishes" allowing users and applications to interact with USB peripherals that use/require ACM support.

The existence of the kernel driver does not mean the OS or even the applications can use it. Can you provide Android documentation regarding apps or the OS actually using this if you think otherwise?

Also, this isn't even enabled on stock? GrapheneOS defconfigs are based on stock.

It's not clear what you're needing from this or trying to do. This is a kernel driver for [interacting with serial devices and modems](https://www.kernel.org/doc/html/latest/usb/acm.html). I suspect you're trying to use [Kali NetHunter](https://www.kali.org/docs/nethunter/nethunter-kernel-6-config-5/) with GrapheneOS and the OS changes necessary for it to be fully functional are not going to be made or supported.

**Comment by ghost** [comment]
There's a reason why the WireGuard kernel module being enabled in stock is pointless attack surface because there is zero evidence that the OS or the apps themselves can use it. If you can find actual evidence that a late 90s USB serial driver is being exposed to the Android OS that apps can use, _and_ find a real-world use case for this it can be looked into.

https://github.com/GrapheneOS/kernel_google_raviole/commit/f47d967986c40a9e20e1f4286234b5c70f4ca701

> The OS does not expose any support for this.

**Comment by s00se** [comment]
> The existence of the kernel driver does not mean the OS or even the applications can use it. Can you provide Android documentation regarding apps or the OS actually using this if you think otherwise?

I am aware that just because the kernel supports it doesn't mean the OS, or any userland applications do. That is not the case here, as AOSP does support it as does userland and other applications for Android.
 
> Also, this isn't even enabled on stock? GrapheneOS defconfigs are based on stock.

No, it's not enabled on the stock devices that GrapheneOS supports. Basically all of Graphene**OS** is based on stock AOSP, so what? All the changes should be reverted then because it's based on stock? Absurd reasoning that because stock doesn't do it, it shouldn't be done. The entire purpose behind GrapheneOS is to do things that stock doesn't do -- arguably because it increases security.

> It's not clear what you're needing from this or trying to do. This is a kernel driver for [interacting with serial devices and modems](https://www.kernel.org/doc/html/latest/usb/acm.html). I suspect you're trying to use [Kali NetHunter](https://www.kali.org/docs/nethunter/nethunter-kernel-6-config-5/) with GrapheneOS and the OS changes necessary for it to be fully functional are not going to be made or supported.

Unfortunately you suspect incorrect, this has nothing to do with attempting to use Kali NetHunter on GrapheneOS. Those 2 things are clearly at complete ends of the spectrum from each other.

This is a simple kernel driver inclusion, there's nothing malicious going on here. What is the actual concern here with enabling this?

I don't see any type of discussion around including things like the inclusion of kernel support for things far outside the scope of GrapheneOS use like:

```
CONFIG_HID_NINTENDO
CONFIG_HID_PLANTRONICS
CONFIG_HID_PLAYSTATION
CONFIG_PLAYSTATION_FF
CONFIG_HID_SONY
```

**Comment by ghost** [comment]
Those are not useless as those provide input for both USB and Bluetooth controllers and physical keyboards.

You still have not made it clear or told us what you're needing this kernel driver for other than that "this is just a simple kernel driver inclusion". Pointless integrations with zero basis or use-case for them will not be merged.

**Comment by s00se** [comment]
> There's a reason why the WireGuard kernel module being enabled in stock is pointless attack surface because there is zero evidence that the OS or the apps themselves can use it. If you can find actual evidence that a late 90s USB serial driver is being exposed to the Android OS that apps can use, _and_ find a real-world use case for this it can be looked into.
> 
> [GrapheneOS/kernel_google_raviole@f47d967](https://github.com/GrapheneOS/kernel_google_raviole/commit/f47d967986c40a9e20e1f4286234b5c70f4ca701)
> 
> > The OS does not expose any support for this.

So, the WireGuard app, which in theory **and in practice** does opportunistically use a kernel driver if available (granted, it requires escalated privs) provides no 'evidence' that the app actually uses the kernel driver? Please expand on this, cause I am not understanding.

If the reasoning to not include CDC_ACM is due to "pointless attack surface", then just say so and clearly this discussion can stop.

**Comment by ghost** [comment]
> If the reasoning to not include CDC_ACM is due to "pointless attack surface", then just say so and clearly this discussion can stop.

It's more-so you have not told us what you're needing this for or the valid use-case here because we do not merge or include pointless things.

**Pull request closed without merging**
